services:
  metasearch:
    image: ghcr.io/bigfabe/metasearch:latest
    container_name: metasearch
    pull_policy: always
    restart: unless-stopped
    command: ["-config", "/config/config.json", "-listen", ":8558"]
    expose:
      - "8558"
    volumes:
      - type: bind
        source: ./config.json
        target: /config/config.json
        read_only: true
        bind:
          create_host_path: false
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    ulimits:
      core: 0
    stop_grace_period: 10s
    networks:
      - lsio

networks:
  lsio:
    external: true
