services:
  metasearch:
    image: ghcr.io/bigfabe/metasearch:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - type: bind
        source: ./config.json
        target: /config/config.json
        read_only: true
        bind:
          create_host_path: false
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    ulimits:
      core: 0
    stop_grace_period: 10s
